#设置语言
language: node_js

# 指定需要sudo权限  
#sudo: required

#设置相应的版本     
node_js: stable    


###### 缓存配置 ######
# 缓存不经常更改的内容，可加快编译速度。
# directories : 目录
cache:
    apt: true
    directories:
        - node_modules 

        
###### 在安装之前 ######
before_install:
    - export TZ='Asia/Shanghai' # 更改时区


###### 安装 ######
install:
  - npm install  #安装hexo及插件(库中没有node_modules，有package.json文件时)

  
###### 脚本 ######
script:
  - chmod 777 ./node_modules/.bin/hexo       #修改权限
  - hexo clean                               #清除
  # - hexo g && gulp                         #生成(需要安装gulp插件)
  - hexo g                                   #生成


###### 脚本之后 ######
after_script:

  #------------START 本地仓库初始化 ------------#
  ## 克隆并检出分支，然后复制 .git 数据库到指定目录
  ## GH_REF是最下面配置的仓库地址
  - git clone https://${GH_REF} .deploy_git  
  - cd .deploy_git
  - git checkout master
  - cd ../
  ## 这一步之前的操作是为了保留master分支的提交记录，
  ## 不然每次git init的话只有1条commit
  - mv .deploy_git/.git/ ./public/   
  #------------END 本地仓库初始化 ------------#

  
  #------------START 本地仓库配置 ------------#
  ## public 目录已是git仓库，且保留了以往的提交记录，可根据实际需求检出文件
  - cd ./public
  - git checkout .gitignore                   # 个人需求
  - git checkout README.md                    # 个人需求  
  - git config user.name "kuma8866"           # 配置name
  - git config user.email "kuma8866@163.com"  # 配置email
  - git add .
  - git commit -m "Travis CI 自动构建在 `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间，跟上面更改时区配合
  #------------END 本地仓库配置 ------------#
  
  
  #------------START 推送配置 ------------#
  ## 可配置多个远程仓库
  
  ## Github 
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master  #Travis_Token是在Travis中配置token的名称
  
  ## gitee
  
  ## Coding
  #------------END 推送配置 ------------#


###### 分支监控 ######
# 博客源码托管在独立repo则不用设置此项
branches:
  only:
    - Hexo  #只监控指定分支   


###### 变量配置 ######
env:
 global:  
   - GH_REF: github.com/KumaNNN/KumaNNN.github.io.git    #设置GH_REF，注意根据实际更改

   
 
###### 配置通知 ######
#（电子邮件，IRC，campfire 等）
# 请更新这一部分，以满足您的需求！
# https://docs.travis-ci.com/user/notifications/

# notifications:
  # email:
    # - 1147727180@qq.com
    # - mtianyan@outlook.com
  # on_success: change
  # on_failure: always