# Hexo 站点配置文件
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 网站配置(Site) 
title: Kuma's Blog
subtitle: Kuma桑の博客，Hexo强力驱动
description: 爱分享，爱技术，爱生活。
keywords:  Html Javascript CSS PHP
author: Kuma
language: zh-CN
timezone: Asia/Shanghai

# 网址(URL) 
##  如果你的站点要放入子目录, 请将url设置为'http://yoursite.com/child' 并将根目录设置为'/child/'
url: https://kumannn.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# 目录(Directory) 
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - README.md

# 文章(Writing) 
new_post_name: :title.md # 新建文章的文件名
default_layout: post
titlecase: false # 转换标题为首字母大写
external_link: true # 在新选项卡中打开外部链接
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# 主页设置(Home page setting)  
# path: 你的博客首页根路径 (默认 = '')
# per_page: 每页显示文章数量 (0 = 禁用分页)
# order_by: 文章排序 (默认为按日期降序)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# 分类和标签(Category & Tag)
default_category: uncategorized
category_map:
tag_map:

# 日期/时间格式(Date/Time format) 
## Hexo 使用 Moment.js 来解析和显示时间
## 你可以自定义日期格式在如下所定义范围内
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# 分页(Pagination) 
## 设置 per_page 为0时禁用分页
per_page: 10
pagination_dir: page

# 扩展(Extensions) 
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# 部署(Deployment) 
## Docs: https://hexo.io/docs/deployment.html
## 因不用自带的Hexo d 部署，所以都注释掉
deploy:
## SSH方式
# type: git
# repo:  
#   github: git@github.com:KumaNNN/hexo.git,master

## HTTPS方式
#  type: git
#  repo: https://github.com/KumaNNN/KumaNNN.github.io.git
#  branch: master
#  message:  

  
include:
  - .nojekyll